blank_issues_enabled: false
contact_links:
  - name: GitHub Community Forum
    url: https://github.community/
    about: Ask questions and discuss the roadmap here.
  - name: GitHub Support - Feedback
    url: https://support.github.com/contact/feedback
    about: Share your feedback with the GitHub team.
